In [1]:
#Import dataset
import pandas as pd
import numpy as np

data = pd.read_csv ( 'cardio_train.csv' , sep = ";" )

In [3]:
data

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0        988  22469       1     155    69.0    130     80            2     2   
1        989  14648       1     163    71.0    110     70            1     1   
2        990  21901       1     165    70.0    120     80            1     1   
3        991  14549       2     165    85.0    120     80            1     1   
4        992  23393       1     155    62.0    120     80            1     1   
...      ...    ...     ...     ...     ...    ...    ...          ...   ...   
69296  99993  19240       2     168    76.0    120     80            1     1   
69297  99995  22601       1     158   126.0    140     90            2     2   
69298  99996  19066       2     183   105.0    180     90            3     1   
69299  99998  22431       1     163    72.0    135     80            1     2   
69300  99999  20540       1     170    72.0    120     80            2     1   

       smoke  alco  active  cardio  
0          0     0       1       0  
1          0     0       1       1  
2          0     0       1       0  
3          1     1       1       0  
4          0     0       1       0  
...      ...   ...     ...     ...  
69296      1     0       1       0  
69297      0     0       1       1  
69298      0     1       0       1  
69299      0     0       0       1  
69300      0     0       1       0  

[69301 rows x 13 columns]

In [4]:
# for i in range ( 0 , len(data['age']) ):
data['age'] = data['age'] / 360

In [5]:
# data['age']
data

id        age  gender  height  weight  ap_hi  ap_lo  cholesterol  \
0        988  62.413889       1     155    69.0    130     80            2   
1        989  40.688889       1     163    71.0    110     70            1   
2        990  60.836111       1     165    70.0    120     80            1   
3        991  40.413889       2     165    85.0    120     80            1   
4        992  64.980556       1     155    62.0    120     80            1   
...      ...        ...     ...     ...     ...    ...    ...          ...   
69296  99993  53.444444       2     168    76.0    120     80            1   
69297  99995  62.780556       1     158   126.0    140     90            2   
69298  99996  52.961111       2     183   105.0    180     90            3   
69299  99998  62.308333       1     163    72.0    135     80            1   
69300  99999  57.055556       1     170    72.0    120     80            2   

       gluc  smoke  alco  active  cardio  
0         2      0     0       1       0  
1         1      0     0       1       1  
2         1      0     0       1       0  
3         1      1     1       1       0  
4         1      0     0       1       0  
...     ...    ...   ...     ...     ...  
69296     1      1     0       1       0  
69297     2      0     0       1       1  
69298     1      0     1       0       1  
69299     2      0     0       0       1  
69300     1      0     0       1       0  

[69301 rows x 13 columns]

In [8]:
# drop from the 13 column, cardio as it is the output , and the id as it has no change on the output
X = data.drop(['cardio','id','height'], axis=1)
y = data['cardio']
X 
# print the first two rows
# print(X.head(2))

age  gender  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0      62.413889       1    69.0    130     80            2     2      0   
1      40.688889       1    71.0    110     70            1     1      0   
2      60.836111       1    70.0    120     80            1     1      0   
3      40.413889       2    85.0    120     80            1     1      1   
4      64.980556       1    62.0    120     80            1     1      0   
...          ...     ...     ...    ...    ...          ...   ...    ...   
69296  53.444444       2    76.0    120     80            1     1      1   
69297  62.780556       1   126.0    140     90            2     2      0   
69298  52.961111       2   105.0    180     90            3     1      0   
69299  62.308333       1    72.0    135     80            1     2      0   
69300  57.055556       1    72.0    120     80            2     1      0   

       alco  active  
0         0       1  
1         0       1  
2         0       1  
3         1       1  
4         0       1  
...     ...     ...  
69296     0       1  
69297     0       1  
69298     1       0  
69299     0       0  
69300     0       1  

[69301 rows x 10 columns]

In [7]:
# import seaborn as sns
# import matplotlib.pyplot as plt

# sns.set(rc = {'figure.figsize':(15,8)})
# sns.countplot(x='age',hue='cardio',data=data,palette='colorblind',edgecolor=sns.color_palette('dark',n_colors=1))

In [9]:
#Splitting to training and testing
from sklearn.model_selection import train_test_split
# split the data into 70% train, 30% test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print(X_train.shape)
print(y_test.shape)

(48510, 10)
(20791,)


In [10]:
X_train

age  gender  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
35254  40.586111       2    76.0    120     70            1     1      1   
46088  60.266667       2    61.0    130     80            3     3      0   
24188  50.683333       1    66.0    140     90            1     1      0   
26764  44.486111       2    82.0    110     80            1     1      0   
31399  42.705556       1    74.0    150     90            1     1      0   
...          ...     ...     ...    ...    ...          ...   ...    ...   
64066  65.075000       1    83.0    160    100            2     1      0   
13313  60.827778       2    96.0    170     80            2     2      0   
54857  42.113889       1    70.0    130     70            1     1      0   
45576  40.525000       1    83.0    110     70            2     1      0   
48426  46.386111       1    58.0    140     90            1     1      0   

       alco  active  
35254     0       1  
46088     1       1  
24188     0       1  
26764     0       1  
31399     0       1  
...     ...     ...  
64066     0       1  
13313     0       1  
54857     0       1  
45576     0       1  
48426     0       0  

[48510 rows x 10 columns]

In [12]:
#Train the model using Multi-Layer perception
from sklearn.neural_network import MLPClassifier

In [13]:
mlp = MLPClassifier( activation='relu')
mlp

MLPClassifier()

In [14]:
X_train.values

array([[40.58611111,  2.        , 76.        , ...,  1.        ,
         0.        ,  1.        ],
       [60.26666667,  2.        , 61.        , ...,  0.        ,
         1.        ,  1.        ],
       [50.68333333,  1.        , 66.        , ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [42.11388889,  1.        , 70.        , ...,  0.        ,
         0.        ,  1.        ],
       [40.525     ,  1.        , 83.        , ...,  0.        ,
         0.        ,  1.        ],
       [46.38611111,  1.        , 58.        , ...,  0.        ,
         0.        ,  0.        ]])

In [15]:
#Training
# fit 70% of the data to do the train
mlp.fit(X_train,y_train)

MLPClassifier()

In [17]:
# get the last row in the data
X_test[-1:]

age  gender  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
60551  44.166667       1    82.0    120     80            1     1      0   

       alco  active  
60551     0       1

In [18]:
#Testing
# predict the 30% of the data set as a test for the training phase on 70% of the data
pred = mlp.predict(X_test)
pred

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
# a percentage to hoe accurate the model test the data
accuracy_score(y_test, pred)
# the model is good cause acc = 72.2 %

0.7257948150642105

In [23]:
mlp.predict([[ 44.166667,1,82.0,120,80,1,1,0,0,1 ]])

array([0], dtype=int64)

In [26]:
mlp.predict([[ 62.413889,1,82.2,155,69.0,130,80,2,2,0 ]])  

array([1], dtype=int64)

In [27]:
mlp.predict([[ 62.780556,1,100,158,126.0,140,90,2,2,0 ]])  

array([1], dtype=int64)

In [28]:
import pickle

In [29]:
# save the Module to use it in the web application
data = {"model": mlp}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)

In [30]:
with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

In [31]:
mlp_loaded = data["model"]

In [33]:
mlp_loaded.predict([[49,1,120,170,61.0,110,70,1,1,0 ]])

array([1], dtype=int64)